apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "backup.name" . }}-cm"
  labels:
    {{- include "backup.labels" . | nindent 4 }}
data:
  app.yml: |
    MINIO_ADDR: {{ .Values.minio.addr }}
    MINIO_BUCKET: {{ .Values.minio.bucket }}
    LOGLEVEL: {{ .Values.logLevel }}
{{- with .Values.backupConfigs }}
    {{- toYaml . | nindent 4 }}
{{- end }}
