apiVersion: v1
kind: Service
metadata:
  name: {{ include "drone.fullname" . }}
  labels:
    {{- include "drone.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: drone
      protocol: TCP
      name: drone
  selector:
    {{- include "drone.selectorLabels" . | nindent 4 }}
